# Generated by Django 5.0.7 on 2024-08-31 15:26

import apps.citizenRequests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudOIRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('tema', models.CharField(max_length=255)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_maxima_respuesta', models.DateField()),
                ('fecha_respuesta_entregada', models.DateField(blank=True, null=True)),
                ('fecha_envio_funcionario', models.DateField(blank=True, null=True)),
                ('fecha_recepcion_descargo', models.DateField(blank=True, null=True)),
                ('texto_solicitud', models.TextField()),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('rut_usuario', models.CharField(max_length=12)),
                ('funcionario_aludido', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.area')),
                ('atingencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.atingencia')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estado_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.estadorespuesta')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.genero')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.sector')),
                ('tipo_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.tiporespuesta')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.tiposolicitud')),
                ('via_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizenRequests.viaingreso')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.citizenRequests.models.archivo_solicitud_path)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='citizenRequests.solicitudoirs')),
            ],
        ),
    ]
