# Generated by Django 5.0.7 on 2024-09-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizenRequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosolicitud',
            name='descripcion',
            field=models.CharField(choices=[('correo_enviado_funcionario', 'Correo enviado a funcionario'), ('Solicitud', 'Solicitud'), ('correo_recibido_funcionario', 'Correo recibido de funcionario'), ('respuesta_enviada', 'Respuesta enviada a usuario'), ('otro_documento', 'Otro documento')], max_length=255),
        ),
    ]
